# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [whois, Wiki]
patreon: # Replace with a single Patreon username sars
open_collective: # Replace with a single Open Collective username hunterz.io
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel npm install --save-dev karma-babel-preprocessor @babel/core
community_bridge: # Replace with a single Community Bridge project-name e.g., tor
liberapay: # Replace with a single Liberapay username opera
issuehunt: # Replace with a single IssueHunt username lions
otechie: # Replace with a single Otechie username bears
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://pornhub.com','https://www.bing.com/aclk?ld=e80Kd2eB1RdS6X_41v5GoUfDVUCUzLOvex6UBGuVqVvCVICntnO7QCjy7bpNw5pNHIOhP2XdfdcvyHyBdSYs5jtizpZmbcD4EZ_ZA14ds2c0VJh_DguN_V3sEDdBRkaYMyGV7BqPkTKQgZlgJ13V-pmvfw7rASLdSkJu_rezqNCMhqlnq3DFDzo5ool4IKtnZCLgpJtg&u=aHR0cHMlM2ElMmYlMmZ3d3cua2xpbmVzcGVjdGVyLmNvbSUyZnJvdW5kdXAtY2FuY2VyLWxhd3N1aXRzLmh0bWwlM2Ztc2Nsa2lkJTNkYjljNmFmZTk5ZGU3MWY5YjNjZWZmMDJjN2E4ZjlmNmQ&rlid=b9c6afe99de71f9b3ceff02c7a8f9f6d','https://priceonomics.com/the-priceonomics-data-studio/','https://mad.org','https://'https://www.ice.gov/cornerstone']
